In [2]:
import pandas as pd

In [3]:
frame = pd.DataFrame({'numbers':range(10),'chars':['a']*10})

In [4]:
frame

chars  numbers
0     a        0
1     a        1
2     a        2
3     a        3
4     a        4
5     a        5
6     a        6
7     a        7
8     a        8
9     a        9

In [8]:
frame = pd.read_csv('D:/Courses/Math and Python for data analysis/Week2/dataset.tsv', header=0, sep = '\t')

In [9]:
frame

Name       Birth       City  Position
0      Иванов А.А.  22.03.1980     Москва       NaN
1     Сорокин И.В.  07.08.1965  Волгоград   инженер
2       Белов М.М.  13.02.1980     Ростов  менеджер
3  Мельникова Д.С.  15.04.1985     Ростов       NaN
4      Рыбина Е.П.  19.11.1985     Москва   инженер
5     Костров С.О.  31.05.1985     Москва    стажер

In [12]:
frame.columns

Index(['Name', 'Birth', 'City', 'Position'], dtype='object')

In [13]:
frame.shape

(6, 4)

In [15]:
new_line = {'Name':'Petrov', 'Birth':'22.03.1990', 'City':'Penza'}
frame.append(new_line, ignore_index=True)

Name       Birth       City  Position
0      Иванов А.А.  22.03.1980     Москва       NaN
1     Сорокин И.В.  07.08.1965  Волгоград   инженер
2       Белов М.М.  13.02.1980     Ростов  менеджер
3  Мельникова Д.С.  15.04.1985     Ростов       NaN
4      Рыбина Е.П.  19.11.1985     Москва   инженер
5     Костров С.О.  31.05.1985     Москва    стажер
6           Petrov  22.03.1990      Penza       NaN

In [16]:
frame

Name       Birth       City  Position
0      Иванов А.А.  22.03.1980     Москва       NaN
1     Сорокин И.В.  07.08.1965  Волгоград   инженер
2       Белов М.М.  13.02.1980     Ростов  менеджер
3  Мельникова Д.С.  15.04.1985     Ростов       NaN
4      Рыбина Е.П.  19.11.1985     Москва   инженер
5     Костров С.О.  31.05.1985     Москва    стажер

In [17]:
frame = frame.append(new_line, ignore_index=True)

In [18]:
frame

Name       Birth       City  Position
0      Иванов А.А.  22.03.1980     Москва       NaN
1     Сорокин И.В.  07.08.1965  Волгоград   инженер
2       Белов М.М.  13.02.1980     Ростов  менеджер
3  Мельникова Д.С.  15.04.1985     Ростов       NaN
4      Рыбина Е.П.  19.11.1985     Москва   инженер
5     Костров С.О.  31.05.1985     Москва    стажер
6           Petrov  22.03.1990      Penza       NaN

In [20]:
frame['IsStudent']=[False]*5 + [True]*2

In [21]:
frame

Name       Birth       City  Position IsStudent
0      Иванов А.А.  22.03.1980     Москва       NaN     False
1     Сорокин И.В.  07.08.1965  Волгоград   инженер     False
2       Белов М.М.  13.02.1980     Ростов  менеджер     False
3  Мельникова Д.С.  15.04.1985     Ростов       NaN     False
4      Рыбина Е.П.  19.11.1985     Москва   инженер     False
5     Костров С.О.  31.05.1985     Москва    стажер      True
6           Petrov  22.03.1990      Penza       NaN      True

In [24]:
frame.drop([5,6], axis = 0, inplace=True)

In [25]:
frame

Name       Birth       City  Position IsStudent
0      Иванов А.А.  22.03.1980     Москва       NaN     False
1     Сорокин И.В.  07.08.1965  Волгоград   инженер     False
2       Белов М.М.  13.02.1980     Ростов  менеджер     False
3  Мельникова Д.С.  15.04.1985     Ростов       NaN     False
4      Рыбина Е.П.  19.11.1985     Москва   инженер     False

In [27]:
frame.drop('IsStudent', axis = 1, inplace = True)

In [28]:
frame

Name       Birth       City  Position
0      Иванов А.А.  22.03.1980     Москва       NaN
1     Сорокин И.В.  07.08.1965  Волгоград   инженер
2       Белов М.М.  13.02.1980     Ростов  менеджер
3  Мельникова Д.С.  15.04.1985     Ростов       NaN
4      Рыбина Е.П.  19.11.1985     Москва   инженер

In [30]:
frame.to_csv('D:/Courses/Math and Python for data analysis/Week2/new_dataset.csv', sep = ',', header = True, index = None)

In [36]:
type 'D:/Courses/Math and Python for data analysis/Week2/new_dataset.csv'

SyntaxError: invalid syntax (<ipython-input-36-309ccf49f53a>, line 1)

In [38]:
frame = pd.read_csv('D:/Courses/Math and Python for data analysis/Week2/dataset.tsv', sep = '\t', header = 0)
frame

Name       Birth       City  Position
0      Иванов А.А.  22.03.1980     Москва       NaN
1     Сорокин И.В.  07.08.1965  Волгоград   инженер
2       Белов М.М.  13.02.1980     Ростов  менеджер
3  Мельникова Д.С.  15.04.1985     Ростов       NaN
4      Рыбина Е.П.  19.11.1985     Москва   инженер
5     Костров С.О.  31.05.1985     Москва    стажер

In [39]:
frame.dtypes

Name        object
Birth       object
City        object
Position    object
dtype: object

In [40]:
frame.Birth = frame.Birth.apply(pd.to_datetime)

In [41]:
frame

Name      Birth       City  Position
0      Иванов А.А. 1980-03-22     Москва       NaN
1     Сорокин И.В. 1965-07-08  Волгоград   инженер
2       Белов М.М. 1980-02-13     Ростов  менеджер
3  Мельникова Д.С. 1985-04-15     Ростов       NaN
4      Рыбина Е.П. 1985-11-19     Москва   инженер
5     Костров С.О. 1985-05-31     Москва    стажер

In [42]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
Name        6 non-null object
Birth       6 non-null datetime64[ns]
City        6 non-null object
Position    4 non-null object
dtypes: datetime64[ns](1), object(3)
memory usage: 272.0+ bytes


In [43]:
frame.fillna('worker', inplace = True)
frame

Name      Birth       City  Position
0      Иванов А.А. 1980-03-22     Москва    worker
1     Сорокин И.В. 1965-07-08  Волгоград   инженер
2       Белов М.М. 1980-02-13     Ростов  менеджер
3  Мельникова Д.С. 1985-04-15     Ростов    worker
4      Рыбина Е.П. 1985-11-19     Москва   инженер
5     Костров С.О. 1985-05-31     Москва    стажер

In [45]:
frame.Position

0      worker
1     инженер
2    менеджер
3      worker
4     инженер
5      стажер
Name: Position, dtype: object

In [46]:
frame[['Name', 'Position']]

Name  Position
0      Иванов А.А.    worker
1     Сорокин И.В.   инженер
2       Белов М.М.  менеджер
3  Мельникова Д.С.    worker
4      Рыбина Е.П.   инженер
5     Костров С.О.    стажер

In [47]:
frame.head(3)

Name      Birth       City  Position
0   Иванов А.А. 1980-03-22     Москва    worker
1  Сорокин И.В. 1965-07-08  Волгоград   инженер
2    Белов М.М. 1980-02-13     Ростов  менеджер

In [48]:
frame[:3]

Name      Birth       City  Position
0   Иванов А.А. 1980-03-22     Москва    worker
1  Сорокин И.В. 1965-07-08  Волгоград   инженер
2    Белов М.М. 1980-02-13     Ростов  менеджер

In [49]:
frame.loc[[1,3,5], ['Name', 'City']]

Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [50]:
frame.iloc[[1,3,5], [0,2]]

Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [51]:
frame.ix[[1,3,5], ['Name', 'City']]

Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [52]:
frame.ix[[1,3,5], [0,2]]

Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [53]:
frame[frame.Birth >= pd.datetime(1985,1,1)]

Name      Birth    City Position
3  Мельникова Д.С. 1985-04-15  Ростов   worker
4      Рыбина Е.П. 1985-11-19  Москва  инженер
5     Костров С.О. 1985-05-31  Москва   стажер

In [54]:
frame[(frame.Birth >= pd.datetime(1985,1,1)) & (frame.City != 'Москва')]

Name      Birth    City Position
3  Мельникова Д.С. 1985-04-15  Ростов   worker

In [55]:
frame[(frame.Birth >= pd.datetime(1985,1,1)) | (frame.City != 'Москва')]

Name      Birth       City  Position
1     Сорокин И.В. 1965-07-08  Волгоград   инженер
2       Белов М.М. 1980-02-13     Ростов  менеджер
3  Мельникова Д.С. 1985-04-15     Ростов    worker
4      Рыбина Е.П. 1985-11-19     Москва   инженер
5     Костров С.О. 1985-05-31     Москва    стажер

In [58]:
frame.addColumn['IsStudent', [False]*3, [True]*3]

AttributeError: 'DataFrame' object has no attribute 'addColumn'

In [57]:
frame

Name      Birth       City  Position
0      Иванов А.А. 1980-03-22     Москва    worker
1     Сорокин И.В. 1965-07-08  Волгоград   инженер
2       Белов М.М. 1980-02-13     Ростов  менеджер
3  Мельникова Д.С. 1985-04-15     Ростов    worker
4      Рыбина Е.П. 1985-11-19     Москва   инженер
5     Костров С.О. 1985-05-31     Москва    стажер

## Intro to NumPy, SciPy and Matplotlib

In [59]:
import numpy as np

In [60]:
x = [2,3,4,6]
y = np.array(x)

array([2, 3, 4, 6])

In [61]:
x

[2, 3, 4, 6]

In [62]:
y

array([2, 3, 4, 6])

In [70]:
print(y[2])

4


In [71]:
y[y>3]

array([4, 6])

In [72]:
y*5

array([10, 15, 20, 30])

In [73]:
x*5

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]

In [74]:
y**2

array([ 4,  9, 16, 36])

In [76]:
matrix = [[1,2,4], [3,1,0]]
np_array = np.array(matrix)

In [77]:
matrix[1][2]

0

In [78]:
np_array[1,2]

0

In [81]:
np.random.rand(4,5)

array([[  9.27690330e-01,   1.43778135e-01,   3.80023240e-01,
          2.96845837e-01,   2.53172484e-02],
       [  2.28850130e-01,   2.04769849e-01,   5.80876555e-01,
          8.42834192e-04,   1.26993693e-01],
       [  8.06146140e-01,   1.41855230e-01,   5.44336155e-01,
          8.04046428e-01,   3.55383198e-03],
       [  9.34432340e-01,   9.44537789e-01,   5.24932003e-01,
          8.91171892e-01,   7.59864877e-01]])

In [82]:
np.arange(0,8,0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9])

In [83]:
from scipy import optimize